name: Build

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: macos-26
    permissions:
      contents: read
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Install XcodeGen
        run: brew install xcodegen

      - name: Generate Xcode project
        run: xcodegen

      - name: Build
        run: xcodebuild -project Knob.xcodeproj -scheme Knob -configuration Release -derivedDataPath build

      - name: Upload artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: Knob.app
          path: build/Build/Products/Release/Knob.app
